---
# tasks file for modify_vm
- name: Include vars for Sat User
  include_vars: user.yml

- name: Lookup the VM we are working with
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "vcenter.randalllabs.com"
    vcenter_username: "administrator@vsphere.randall"
    vcenter_password: "{{ vmware_pass }}"
    vcenter_validate_certs: false
    filter_names:
      - "{{ ansible_hostname }}"
  register: vm_search
  delegate_to: localhost

- name: Lookup the VM we are working with
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "vcenter.randalllabs.com"
    vcenter_username: "administrator@vsphere.randall"
    vcenter_password: "{{ vmware_pass }}"
    vcenter_validate_certs: false
    vm: "{{ vm_search.value[0].vm }}"
  register: search_results
  delegate_to: localhost

- name: Output VM info
  debug:
    var: search_results

- name: Get VM info
  community.vmware.vmware_guest_disk_info:
    hostname: "vcenter.randalllabs.com"
    username: "administrator@vsphere.randall"
    password: "{{ vmware_pass }}"
    validate_certs: "{{ cert_val }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    datacenter: HPG8
    name: "{{ ansible_hostname }}"
  delegate_to: localhost